### ISSUE TITLE
Allow players to join mid session

### ISSUE THREAD

**Issue by pckv** [magicsgram/wordleoff#1]
As a casual game it would be very convenient if one could host a lobby that friends could join and leave whenever they want. Especially considering games might take a while. This would allow for less engaging games where everyone can freely place a word when they have some time and the game would be open in the background.

My proposal is that you join either in a new spectate mode, which would only indicate colors of the letters, or just god mode. When the game resets the player would be added to the game.

**Comment by magicsgram** [comment]
I'm thinking about allowing joining in god mode, although that kinda allows people to cheat by joining w/ a separate window.
But I guess I shouldn't worry too much about cheating, because it isn't that difficult to snoop into websocket traffic and cheat anyways. (I'm not too worry about cheating. There's very little incentive to cheat over your friends. That kinda ruins the fun for them, and I want cheaters to lose interest and leave the game. I don't plan to support random lobby anytime soon.

Btw, these changes may be implemented once start saving things to the database, not within memory. (This whole project is WIP and is a proof of concept for now)

Thanks for your feedback!

**Comment by magicsgram** [comment]
@pckv now you can join mid-session.
I was debating myself whether I should have new people join as God Mode, but have them catch up w/ the guesses.
I chose the latter, because the implementation was literally like 2 lines of changes.

Will, evaluate further if it's better to have people join mid-session in God Mode.
